version: '3.1'

services:
  clonex-graph-node:
    image: graphprotocol/graph-node:v0.33.0
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: gojo
      postgres_pass: hodor
      postgres_db: clonexgraphdb
      ipfs: 'ipfs:5020'
      GRAPH_ALLOW__NON_DETERMINISTIC_IPFS: 1
      ETHEREUM: "mainnet:https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
      RUST_LOG: info
      GRAPH_LOG: info, error

  ipfs:
    image: ipfs/go-ipfs:v0.17.0 
    ports:
      - '5001:5001'
    volumes:
      - ./clonex_data/ipfs:/data/ipfs 

  postgres:
    image: postgres:latest
    ports:
      - '6464:6464'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: gojo
      POSTGRES_PASSWORD: hodor
      POSTGRES_DB: clonexgraphdb
    volumes:
      - ./clonex_data/postgres:/var/lib/postgresql/data  
